### ISSUE TITLE
Crash when pressing Backspace on Windows

### ISSUE THREAD

**Issue by akavel** [murarth/rusti#89]
After starting and pressing <kbd>Backspace</kbd>, the app crashes (regardless if it's first Backspace, or after typing something and trying to correct it):
```
C:\prog\rusti>cargo run -v
       Fresh utf8-ranges v0.1.3
       Fresh void v1.0.2
       Fresh libc v0.2.15
       Fresh log v0.3.6
       Fresh bitflags v0.4.0
       Fresh winapi v0.2.8
       Fresh rand v0.3.14
       Fresh memchr v0.1.11
       Fresh winapi-build v0.1.1
       Fresh cfg-if v0.1.0
       Fresh getopts v0.2.14
       Fresh aho-corasick v0.5.2
       Fresh regex-syntax v0.3.4
       Fresh assert_matches v1.0.1
       Fresh semver v0.1.20
       Fresh shell32-sys v0.1.1
       Fresh ole32-sys v0.2.0
       Fresh rustc_version v0.1.7
       Fresh kernel32-sys v0.2.2
       Fresh tempfile v1.1.3
       Fresh thread-id v2.0.0
       Fresh thread_local v0.2.6
       Fresh regex v0.1.73
       Fresh nix v0.6.0
       Fresh env_logger v0.3.4
       Fresh linefeed v0.1.0
       Fresh rusti v0.0.1 (file:///C:/prog/rusti)
    Finished debug [unoptimized + debuginfo] target(s) in 0.25 secs
     Running `target\debug\rusti.exe`
rusti=> thread 'main' panicked at 'attempted to multiply with overflow', C:\Users\Mateusz\.cargo\registry\src\github.co5
stack backtrace:
   0:         0x65400d0e - <unknown>
   1:         0x653fef6e - <unknown>
   2:         0x653ff7d4 - <unknown>
   3:         0x653ff605 - <unknown>
   4:         0x653ff515 - <unknown>
   5:         0x653ff47c - <unknown>
   6:         0x654388b5 - <unknown>
   7:         0x654387f0 - <unknown>
   8:           0x9a9bf7 - <unknown>
   9:           0x44fdab - <unknown>
  10:           0x45b424 - <unknown>
  11:           0x45fd8a - <unknown>
  12:           0x454748 - <unknown>
  13:           0x46a25b - <unknown>
  14:           0x6d30af - <unknown>
  15:           0x6d2757 - <unknown>
  16:           0x6d6afd - <unknown>
  17:           0x6dcada - <unknown>
  18:           0x4014fe - <unknown>
  19:         0x653ff3ec - <unknown>
  20:         0x654100e8 - <unknown>
  21:         0x653fe4f4 - <unknown>
  22:           0x40153a - <unknown>
  23:           0x4013b4 - <unknown>
  24:           0x4014e7 - <unknown>
  25:     0x7ff9612d8101 - <unknown>
error: Process didn't exit successfully: `target\debug\rusti.exe` (exit code: 101)

C:\prog\rusti>rustc --version
rustc 1.12.0-nightly (7333c4ac2 2016-07-31)
```

**Comment by akavel** [comment]
Running under nightly-...-msvc (instead of -gnu I used originally), I got more detailed stacktrace:
```
C:\prog\rusti>rustup run nightly-2016-08-01-x86_64-pc-windows-msvc cargo run -v
       Fresh getopts v0.2.14
       Fresh regex-syntax v0.3.4
       Fresh libc v0.2.15
       Fresh winapi v0.2.8
       Fresh bitflags v0.4.0
       Fresh log v0.3.6
       Fresh winapi-build v0.1.1
       Fresh memchr v0.1.11
       Fresh cfg-if v0.1.0
       Fresh assert_matches v1.0.1
       Fresh aho-corasick v0.5.2
       Fresh utf8-ranges v0.1.3
       Fresh void v1.0.2
       Fresh ole32-sys v0.2.0
       Fresh kernel32-sys v0.2.2
       Fresh semver v0.1.20
       Fresh rand v0.3.14
       Fresh shell32-sys v0.1.1
       Fresh thread-id v2.0.0
       Fresh rustc_version v0.1.7
       Fresh tempfile v1.1.3
       Fresh thread_local v0.2.6
       Fresh regex v0.1.73
       Fresh env_logger v0.3.4
       Fresh nix v0.6.0
       Fresh linefeed v0.1.0
       Fresh rusti v0.0.1 (file:///C:/prog/rusti)
    Finished debug [unoptimized + debuginfo] target(s) in 0.21 secs
     Running `target\debug\rusti.exe`
rusti=> thread 'main' panicked at 'attempted to multiply with overflow', C:\Users\Mateusz\.cargo\registry\src\github.co5
stack backtrace:
   0:     0x7ff93c42c59b - _<std..rand..OsRng as rand..Rng>::fill_bytes::h9c57846bf319fa5d
   1:     0x7ff93c42a4ea - std::panicking::Location::line::h978f36db9184e516
   2:     0x7ff93c42ad1d - std::panicking::rust_panic_with_hook::h105c3d42fcd2fb5e
   3:     0x7ff93c42ab4b - std::panicking::begin_panic_fmt::h20f5943904e5791d
   4:     0x7ff93c42aa0f - std::panicking::begin_panic_fmt::h20f5943904e5791d
   5:     0x7ff93c42a97c - rust_begin_unwind
   6:     0x7ff93c4514b5 - core::panicking::panic_fmt::h19323e466869c656
   7:     0x7ff93c4513f0 - core::panicking::panic::hbfac80217e56ecbe
   8:     0x7ff7d713a68d - clear_to_screen_end
                        at C:\Users\Mateusz\.cargo\registry\src\github.com-1ecc6299db9ec823\linefeed-0.1.0\src\windows\5
   9:     0x7ff7d6e6e9dc - delete_range<linefeed::sys::console::Console,core::ops::Range<usize>>
                        at C:\Users\Mateusz\.cargo\registry\src\github.com-1ecc6299db9ec823\linefeed-0.1.0\src\reader.r9
  10:     0x7ff7d6e7a971 - execute_command<linefeed::sys::console::Console>
                        at C:\Users\Mateusz\.cargo\registry\src\github.com-1ecc6299db9ec823\linefeed-0.1.0\src\reader.r2
  11:     0x7ff7d6e8215e - execute_sequence<linefeed::sys::console::Console>
                        at C:\Users\Mateusz\.cargo\registry\src\github.com-1ecc6299db9ec823\linefeed-0.1.0\src\reader.r2
  12:     0x7ff7d6e742b4 - read_line_impl<linefeed::sys::console::Console>
                        at C:\Users\Mateusz\.cargo\registry\src\github.com-1ecc6299db9ec823\linefeed-0.1.0\src\reader.r4
  13:     0x7ff7d6e8ea70 - read_line<linefeed::sys::console::Console>
                        at C:\Users\Mateusz\.cargo\registry\src\github.com-1ecc6299db9ec823\linefeed-0.1.0\src\reader.r7
  14:     0x7ff7d700527f - read_line
                        at C:\prog\rusti\src\rusti\input.rs:195
  15:     0x7ff7d70047f2 - read_input
                        at C:\prog\rusti\src\rusti\input.rs:125
  16:     0x7ff7d7008616 - run
                        at C:\prog\rusti\src\rusti\repl.rs:155
  17:     0x7ff7d700f4c1 - run
                        at C:\prog\rusti\src\rusti\lib.rs:109
  18:     0x7ff7d6e3100e - main
                        at C:\prog\rusti\src\bin\rusti.rs:12
  19:     0x7ff93c42a8ec - std::panicking::Location::line::h978f36db9184e516
  20:     0x7ff93c434911 - _rust_maybe_catch_panic
  21:     0x7ff93c4299d4 - std::rt::lang_start::hfe9ab243c60ffb9b
  22:     0x7ff7d6e31049 - main
  23:     0x7ff7d714e203 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:255
  24:     0x7ff9612d8101 - BaseThreadInitThunk
error: Process didn't exit successfully: `target\debug\rusti.exe` (exit code: 101)
```

**Comment by murarth** [comment]
I've pushed a fix for this. It turns out I need to be more careful with 16-bit integers. Thanks for the issue.

**Comment by akavel** [comment]
Um, not there yet, I believe? I can't see any new commits

**Comment by murarth** [comment]
Oh, I'm sorry. I had pushed the fix to linefeed, the crate that handles input reading, but neglected to update the dependency here. I've definitely pushed it now. Double checked. I promise.

**Comment by akavel** [comment]
I confirm this is now fixed.
